e

diff --git a/binarios/herrabin b/binarios/herrabin
--- a/binarios/herrabin
+++ b/binarios/herrabin
@@ -1,113 +1,126 @@
 #!/bin/bash
 
-
-# Función para verificar si un paquete está instalado
-
-paquetes=("sudo" "curl" "git" "kitty" "nano" "sudo" "zsh" "xclip" "python3" "bat" "lsd" "tldr" "iproute2" "net-tools" "iputils-ping" )
-
-
-# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
-paquete_instalado_apt() {  
-    dpkg -l "$1" | grep -q '^ii'  >/dev/null
-}
-
-# Función para verificar si un paquete está instalado (CentOS/RHEL)
-paquete_instalado_yum() {
-    yum list installed "$1"  >/dev/null
-}
-
-# Función para verificar si un paquete está instalado (Fedora)
-paquete_instalado_dnf() {
-    dnf list installed "$1" >/dev/null
-}
-
-# Función para verificar si un paquete está instalado (Arch Linux)
-paquete_instalado_pacman() {
-    pacman -Qi "$1" >/dev/null
-}
-
-# Detectar el sistema operativo
-if [ -f /etc/os-release ]; then
-    . /etc/os-release
-    OS=$ID
-fi
-
-# Instalar paquetes basados en el sistema operativo
-for paquete in "${paquetes[@]}"; do
-    case $OS in
-        "debian"|"ubuntu"|"kali")
-            if ! paquete_instalado_apt "$paquete"; then
-                echo "Instalando el paquete $paquete..."
-                sudo apt-get install -y "$paquete" >/dev/null
-            fi
-            ;;
-        "centos"|"rhel")
-            if ! paquete_instalado_yum "$paquete"; then
-                echo "Instalando el paquete $paquete..."
-                sudo yum install -y "$paquete" >/dev/null
-            fi
-            ;;
-        "fedora")
-            if ! paquete_instalado_dnf "$paquete"; then
-                echo "Instalando el paquete $paquete..."
-                sudo dnf install -y "$paquete" >/dev/null
-            fi
-            ;;
-        "arch")
-            if ! paquete_instalado_pacman "$paquete"; then
-                echo "Instalando el paquete $paquete..."
-                sudo pacman -S --noconfirm "$paquete" >/dev/null
-            fi
-            ;;
-        *)
+# Verificar si la opción -o está presente
+while getopts "o" opt; do
+    case $opt in
+        o)
+            omitir=true
             ;;
     esac
 done
 
+if [[ $omitir != true ]]; then
 
+    #omitir -o
 
+    # Función para verificar si un paquete está instalado
 
+    paquetes=("sudo" "curl" "git" "kitty" "nano" "sudo" "zsh" "xclip" "python3" "bat" "lsd" "tldr" "iproute2" "net-tools" "iputils-ping" )
 
+    # Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
+    paquete_instalado_apt() {  
+        dpkg -l "$1" | grep -q '^ii'  >/dev/null
+    }
 
-function mktem() {
-    new_dir=$(mktemp -d)
-    echo "Directorio creado en: $new_dir"
-    cd "$new_dir" || return
-    echo "Cambiado al directorio: $PWD"
-}
+    # Función para verificar si un paquete está instalado (CentOS/RHEL)
+    paquete_instalado_yum() {
+        yum list installed "$1"  >/dev/null
+    }
 
+    # Función para verificar si un paquete está instalado (Fedora)
+    paquete_instalado_dnf() {
+        dnf list installed "$1" >/dev/null
+    }
 
+    # Función para verificar si un paquete está instalado (Arch Linux)
+    paquete_instalado_pacman() {
+        pacman -Qi "$1" >/dev/null
+    }
 
+    # Detectar el sistema operativo
+    if [ -f /etc/os-release ]; then
+        . /etc/os-release
+        OS=$ID
+    fi
 
-# Aquí puedes llamar a la función mktem
-mktem
+    # Instalar paquetes basados en el sistema operativo
+    for paquete in "${paquetes[@]}"; do
+        case $OS in
+            "debian"|"ubuntu"|"kali")
+                if ! paquete_instalado_apt "$paquete"; then
+                    echo "Instalando el paquete $paquete..."
+                    sudo apt-get install -y "$paquete" >/dev/null
+                fi
+                ;;
+            "centos"|"rhel")
+                if ! paquete_instalado_yum "$paquete"; then
+                    echo "Instalando el paquete $paquete..."
+                    sudo yum install -y "$paquete" >/dev/null
+                fi
+                ;;
+            "fedora")
+                if ! paquete_instalado_dnf "$paquete"; then
+                    echo "Instalando el paquete $paquete..."
+                    sudo dnf install -y "$paquete" >/dev/null
+                fi
+                ;;
+            "arch")
+                if ! paquete_instalado_pacman "$paquete"; then
+                    echo "Instalando el paquete $paquete..."
+                    sudo pacman -S --noconfirm "$paquete" >/dev/null
+                fi
+                ;;
+            *)
+                ;;
+        esac
+    done
 
-git clone https://github.com/4rji/4rji.git
-cd 4rji/
+    function mktem() {
+        new_dir=$(mktemp -d)
+        echo "Directorio creado en: $new_dir"
+        cd "$new_dir" || return
+        echo "Cambiado al directorio: $PWD"
+    }
 
-./alias.sh
+    # Aquí puedes llamar a la función mktem
+    mktem
 
-sudo cp -f binarios/* /usr/bin/
+    git clone https://github.com/4rji/4rji.git
+    cd 4rji/
 
-echo "binarios actualizados"
-cd
-echo ""
-echo "Si hay: Error opening terminal: xterm-kitty, ejecutar:"
-echo "export TERM=xterm"
+    ./alias.sh
 
+    sudo cp -f binarios/* /usr/bin/
 
+    echo "binarios actualizados"
+    cd
 
+    #hasta aqui termina la omision esto normal
 
+    echo ""
+    echo "_________________________________________________________"
+    echo ""
+
+    echo "Si hay: Error opening terminal: xterm-kitty, ejecutar:"
+    echo "export TERM=xterm"
+
+    echo ""
+    echo "_________________________________________________________"
+    echo ""
+
+fi
 
 #para instalar functions en las bash
 echo ""
+echo "_________________________________________________________"
 echo ""
 
 # Pregunta al usuario
-read -p "¿Quieres instalar las FUNCTION en la bash? (s/N): " respuesta
+read -n1 -p "¿Quieres instalar las FUNCTION en la bash? (s/N): " respuesta
+echo ""
 
 # Define un valor predeterminado si el usuario presiona Enter
-respuesta=${respuesta:-N}
+respuesta=${respuesta:-n}
 
 # Convierte la respuesta a minúsculas para facilitar la comparación
 respuesta=$(echo $respuesta | tr '[:upper:]' '[:lower:]')
@@ -115,20 +128,21 @@ respuesta=$(echo $respuesta | tr '[:upper:]' '[:lower:]')
 # Verifica la respuesta
 if [ "$respuesta" == "s" ]; then
     echo "Ejecutando bashfun..."
-    bashfun
     # Aquí colocas el código para ejecutar bashfun
 else
     echo ""
 fi
 
 echo ""
-
+echo "_________________________________________________________"
+echo ""
 
 # Pregunta al usuario
-read -p "¿Quieres instalar todos ALIAS (s/N): " respuesta
+read -n1 -p "¿Quieres instalar todos ALIAS? (s/N): " respuesta
+echo ""
 
 # Define un valor predeterminado si el usuario presiona Enter
-respuesta=${respuesta:-N}
+respuesta=${respuesta:-n}
 
 # Convierte la respuesta a minúsculas para facilitar la comparación
 respuesta=$(echo $respuesta | tr '[:upper:]' '[:lower:]')
@@ -136,13 +150,13 @@ respuesta=$(echo $respuesta | tr '[:upper:]' '[:lower:]')
 # Verifica la respuesta
 if [ "$respuesta" == "s" ]; then
     echo "instalando todos los alias... herralias"
-    herralias
     # Aquí colocas el código para ejecutar bashfun
 else
     echo ""
 fi
 
-
+echo ""
+echo "_________________________________________________________"
 echo ""
 
 echo " ########### ALERTA.  #################"
@@ -150,12 +164,15 @@ echo ""
 echo "Tarda mucho en instalarse"
 
 echo ""
+echo "_________________________________________________________"
+echo ""
 
 # Pregunta al usuario
-read -p "¿Quieres instalar todos los paquetes de 2-arji (s/N): " respuesta
+read -n1 -p "¿Quieres instalar todos los paquetes de 2-arji? (s/N): " respuesta
+echo ""
 
 # Define un valor predeterminado si el usuario presiona Enter
-respuesta=${respuesta:-N}
+respuesta=${respuesta:-n}
 
 # Convierte la respuesta a minúsculas para facilitar la comparación
 respuesta=$(echo $respuesta | tr '[:upper:]' '[:lower:]')
@@ -163,13 +180,7 @@ respuesta=$(echo $respuesta | tr '[:upper:]' '[:lower:]')
 # Verifica la respuesta
 if [ "$respuesta" == "s" ]; then
     echo "instalando todos los paquetes... 2-4rji"
-    2-4rji >/dev/null
     # Aquí colocas el código para ejecutar bashfun
 else
     echo ""
 fi
-
-
-
-
-
