1

diff --git a/binarios/pgg b/binarios/pgg
--- a/binarios/pgg
+++ b/binarios/pgg
@@ -151,12 +151,12 @@ fi
 
 
 #old version
-''' host="google.com"  # Cambia "google.com" por el host que desees
+#host="google.com"  # Cambia "google.com" por el host que desees
 
-ping -c 1 "$host" > /dev/null 2>&1
+#ping -c 1 "$host" > /dev/null 2>&1
 
-if [[ $? -eq 0 ]]; then
-  echo "The Internet connection is active."
-else
-  echo "Unable to access the Internet."
-fi '''
+#if [[ $? -eq 0 ]]; then
+#  echo "The Internet connection is active."
+#else
+#  echo "Unable to access the Internet."
+#fi 
