Update pgg

diff --git a/binarios/pgg b/binarios/pgg
--- a/binarios/pgg
+++ b/binarios/pgg
@@ -2,7 +2,7 @@
 echo ""
 
 # Lista de paquetes a instalar
-paquetes=("dnsutils" "jq" "systemd" "iproute2" "bat" )
+paquetes=("dnsutils" "jq" "systemd" "iproute2" )
 
 # Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
 paquete_instalado_apt() {  
@@ -64,135 +64,135 @@ done
 
 
 
+# Color codes
+green="\e[32m"
+yellow="\e[33m"
+reset="\e[0m"
 
-
-
-
-# Función para verificar si un paquete está instalado
-###############
- # ****  ****  se comento el mensaje y el sleep time para rapides de iniciacion del sistema *** **** #############
-######################
-
-
-
-
-
-echo "-------   IPs local   -----------"
-
-hostname -I | awk '{print $1 " | " $2}'
-
-echo ""
-
-#echo "----ip_addr_show----"
-#ip -4 addr show | awk '/inet/ && /brd/ {print $NF, $2}'
-
-tempfile=$(mktemp)
-ip -4 addr show | awk '/inet/ && !/127.0.0.1/ {split($2, a, "/"); print $NF, a[1]}' > "$tempfile"
-batcat -l rb "$tempfile"
-
-
-
-
-
-#hostname -I | awk '{print $1 " | " $2 " | " $3}'
-echo ""
-echo "_________________________________________________________"
-#echo ""
-#echo "---------------------------------------------------------"
-echo "      IP publica localmente encontrada con dig"
-
-timeout 2 dig +short myip.opendns.com @resolver1.opendns.com | while read -r ip; do
-    printf "%*s\n" $((($(tput cols) + ${#ip}) / 4)) "$ip"
-done
-
-#timeout 2 dig +short myip.opendns.com @resolver1.opendns.com
-echo "_________________________________________________________"
-echo ""
-
-
-
-echo ""
-
-# Función para comprobar la conexión a Internet
-check_internet_connection() {
-    echo ""
-echo ""
-echo "_________________________________________________________"
-echo ""
-echo "             From ifconfig.me: "
-    ip_address=$(timeout 2s curl -s ifconfig.me)
-printf "%*s\n" $((($(tput cols) + ${#ip_address}) / 4)) "$ip_address"
-
-
-
-#comando para google ping internet active
-   # local host="google.com"  # Cambia "google.com" por el host que desees
-
-  #  ping -c 1 "$host" > /dev/null 2>&1
-
-    if [[ $? -eq 0 ]]; then
- #       echo "        Internet connection is ACTIVE.        "
-#	echo "               Ping google.com                "
-	echo "_________________________________________________________"
+# Funci  n para obtener la interfaz de red
+get_network_interface() {
+    # Verificar si wlan0 existe
+    if ifconfig wlan0 &>/dev/null; then
+        echo "wlan0"
     else
-        echo "No se puede acceder a Internet."
+        # Obtener el nombre de la interfaz de red
+        interface=$(ip route | awk '/default/ {print $5}')
+        echo "$interface"
     fi
 }
 
+# Obtener la interfaz de red
+network_interface=$(get_network_interface)
 
-#echo "---------------------------------------------------------"
-#echo "_________________________________________________________"
+echo -e "\e[33;1m                _______________ INTERFACES _______________\e[0m\n"
+                  
+# Mostrar la direcci  n IP local
+#echo "${yellow}Direcci  n IP local:${reset}"
+ip -4 addr show | awk '/inet/ && !/127.0.0.1/ {split($2, a, "/"); printf "\t\t\t\t%s: %s\n", $NF, a[1]}'
+echo ""
+echo ""
+echo -e "\e[34m                  ___________________________________________________\e[0m"
+# Agregamos el mensaje con la IP local
+echo -e "\n\t\t\t\tTu IP es: $(/usr/sbin/ifconfig "$network_interface" | grep "inet " | awk '{print $2}')\n"
+echo -e "\t\t\t\t  ${green}---   $(whoami)   ---${reset}\n"
 
-# Preguntar si se desea ejecutar el script
-echo "¿Verificar la conexion y IP? [s] )"
+#echo -e "\n\t\t\t ${yellow}*** Puerto de escucha: ***${reset}\n"
+#echo -e "\t\t\t\t  $(grep -E '^#?Port ' /etc/ssh/sshd_config | awk '!/^#/')"
+
+
+
 echo ""
-read -n 1 -t 1 -p "Enter or wait 1s to cancel: " response
+printf "\e[34;1m_________________________________________________________\e[0m\n"
 echo ""
-echo "_________________________________________________________"
+printf "\e[34;1m      IP pública localmente encontrada con dig\e[0m\n"
 echo ""
-# Si la respuesta es 's', ejecuta la verificación
+
+timeout 1.5 dig +short myip.opendns.com @resolver1.opendns.com | while read -r ip; do
+    # Calcula el espaciado necesario para centrar la IP
+    cols=$(tput cols)
+    ip_length=${#ip}
+    spaces=$(( (cols - ip_length) / 2 ))
+
+    # Usa printf para espaciar y luego imprimir la IP en rojo
+    printf "%$((spaces - 35))s\e[31m%s\e[0m\n" "" "$ip"
+
+    #printf "%${spaces}s" ""
+    #printf "\e[31m%s\e[0m\n" "$ip"
+done
+
+printf "\e[34;1m_________________________________________________________\e[0m\n"
+echo ""
+echo ""
+
+
+
+
+
+
+
+check_ip() {
+    local url_list=(
+        'https://ipinfo.io/json'
+        'https://api.myip.com'
+        'https://ifconfig.me/all.json'
+    )
+
+    for url in "${url_list[@]}"; do
+#        echo -e "\e[0mInformacion IP de \e[0m\e[38;5;94m$url...\e[0m"
+        echo -e "\e[38;5;94mInformacion IP de $url...\e[0m"
+
+ #       echo -e "\e[33mInformacion IP de $url...\e[0m"
+        echo ""
+        local request="$(curl -s "$url")"
+        local response="$?"
+
+        if [[ "$response" -ne 0 ]]; then
+            echo "Error al conectar con $url"
+            continue
+        fi
+
+        # Procesar la respuesta dependiendo de la URL
+        if [[ "$url" == "https://ipinfo.io/json" ]]; then
+            echo "$request" | jq -r '.ip, .city, .region, .country, .postal // empty' | awk '{print "\033[33m" $0 "\033[0m"}'
+            return 0
+        elif [[ "$url" == "https://api.myip.com" ]]; then
+            # api.myip.com proporciona ip, country, y country code, pero no ciudad o región
+            echo "$request" | jq -r '.ip, .country // empty' | awk '{print "\033[33m" $0 "\033[0m"}'
+            return 0
+        elif [[ "$url" == "https://ifconfig.me/all.json" ]]; then
+            # ifconfig.me ofrece un conjunto de datos más amplio, pero nos centraremos en ip_addr y country
+            echo "$request" | jq -r '.ip_addr, .country // empty' | awk '{print "\033[33m" $0 "\033[0m"}'
+            return 0
+        fi
+    done
+
+    echo "No se pudo obtener la dirección IP pública desde las fuentes disponibles."
+}
+
+
+
+
+echo -e "\e[36m¿Verificar la conexión y IP? [s/n]\e[0m"
+echo ""
+read -n 1 -t 1.5 -p "Enter o espera 1.5s para cancelar: " response
+echo ""
+echo -e "\e[36m_________________________________________________________\e[0m"
+echo ""
+
 if [[ "$response" == "s" ]]; then
-    check_internet_connection
-    # Guardar la salida de ipinfo.io en un archivo temporal
-    tmpfile=$(mktemp)
-
-    #curl -s ipinfo.io | jq 'del(.loc, .org, .readme)' > "$tmpfile"
-    echo ""
-    echo "              From ipinfo.io:" 
-    curl -s ipinfo.io | jq -r '.ip, .city, .region, .country, .postal'
-    
-    echo ""
-    # Mostrar el contenido del archivo temporal con batcat
-#   batcat -l rb "$tmpfile"
-    # Aquí puedes descomentar la siguiente línea para eliminar el archivo temporal
-    # rm "$tmpfile"
+    check_ip
 else
-    echo ""
-    echo "Cancelado. "
+    echo "Cancelado."
 fi
 
-
-
-
-#old version
-#host="google.com"  # Cambia "google.com" por el host que desees
-
-#ping -c 1 "$host" > /dev/null 2>&1
-
-#if [[ $? -eq 0 ]]; then
-#  echo "The Internet connection is active."
-#else
-#  echo "Unable to access the Internet."
-#fi 
-
-
 echo ""
+
 host="google.com"  # Cambia "google.com" por el host que desees
 
-timeout 2 ping -c 1 "$host" > /dev/null 2>&1
+timeout 1.5 ping -c 1 "$host" > /dev/null 2>&1
 
 if [[ $? -eq 0 ]]; then
-  echo "The Internet connection is active."
+  echo -e "\e[32mThe Internet connection is active.\e[0m"
 else
-  echo "Unable to access the Internet."
+  echo -e "\e[31mUnable to access the Internet.\e[0m"
 fi 
