a

diff --git a/binarios/sshmoni b/binarios/sshmoni
--- a/binarios/sshmoni
+++ b/binarios/sshmoni
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+
 # Función para verificar si un paquete está instalado
 paquete_instalado() {  
     dpkg -l "$1" | grep -q '^ii'  
@@ -13,19 +14,16 @@ for paquete in "${paquetes[@]}"; do
     fi  
 done
 
+
+
 # SSH Port y PID File
 SSH_PORT=22
 PID_FILE="/tmp/pidssh"
 
-# Check if the script is running as root
-if [ "$EUID" -ne 0 ]; then
-    echo "Some process details might not be shown. Please run as root for complete details."
-fi
-
 # Function to check for SSH connections
 check_ssh_connections() {
     > "$PID_FILE"
-    local connections=$(netstat -tnp | grep ':'"$SSH_PORT" | grep 'ESTABLISHED')
+    local connections=$(sudo netstat -tnp | grep ':'"$SSH_PORT" | grep 'ESTABLISHED')
     if [ ! -z "$connections" ]; then
         echo ""
         echo "**********   ALERT : Active SSH connection detected.   ***********"
@@ -34,56 +32,57 @@ check_ssh_connections() {
         echo "$connections" | while IFS= read -r line; do
             local ip=$(echo "$line" | awk '{print $5}')
             local pid=$(echo "$line" | awk '{print $7}' | grep -o '[0-9]*')
-            local user=$(ps -o user= -p "$pid" 2>/dev/null)
+            local user=$(sudo ps -o user= -p "$pid" 2>/dev/null)
             echo "$count) IP: $ip, User: $user, PID: $pid"
             echo "$pid" >> "$PID_FILE"
             ((count++))
         done
+        ask_to_kill_connection
     else
         echo ""
         echo "No active SSH connections at this time."
-	echo ""    
-fi
+        echo ""
+        exit_after_delay
+    fi
+}
+
+# Function to ask the user if they want to kill a connection
+ask_to_kill_connection() {
+    echo ""
+    echo "Enter the number of the connection you want to kill, or press Enter to exit:"
+    read -t 3 -r selection
+
+    if [ -z "$selection" ]; then
+        echo "No selection made or time out. Exiting..."
+        exit 0
+    elif [[ "$selection" =~ ^[0-9]+$ ]]; then
+        handle_connection_selection "$selection"
+    else
+        echo "Invalid selection. Exiting..."
+        exit 1
+    fi
+}
+
+# Function to handle the user's selection
+handle_connection_selection() {
+    local selection=$1
+    mapfile -t pids < "$PID_FILE"
+
+    if [ "$selection" -gt 0 ] && [ "$selection" -le ${#pids[@]} ]; then
+        local selected_pid=${pids[$selection-1]}
+        sudo kill "$selected_pid"
+        echo "Executed 'sudo kill' on PID $selected_pid."
+    else
+        echo "Invalid selection."
+    fi
+}
+
+# Function to exit script after a delay
+exit_after_delay() {
+    echo "Checking again in 4 seconds..."
+    read -t 3
+    exit 0
 }
 
 # Call the check function once
 check_ssh_connections
-
-# Read PIDs into an array
-mapfile -t pids < "$PID_FILE"
-
-# Check if there are no active SSH connections
-if [ ${#pids[@]} -eq 0 ]; then
-    echo "Would you like to start a monitoring loop? (s/Enter):"
-    read -r loop_answer
-    if [[ "$loop_answer" == "s" ]]; then
-        while true; do
-            sudo /usr/bin/sshmoni
-            sleep 2
-        done
-    else
-        exit 0
-    fi
-fi
-
-# Ask which connection to kill
-echo ""
-echo "Enter the number of the connection you want to kill, or press Enter to exit:"
-echo ""
-
-read -r selection
-
-# Check if the user pressed Enter (empty input)
-if [ -z "$selection" ]; then
-    echo "Exit requested."
-    exit 0
-fi
-
-# Convert the selection to a number and check if it's within the valid range
-if [[ "$selection" =~ ^[0-9]+$ ]] && [ "$selection" -gt 0 ] && [ "$selection" -le ${#pids[@]} ]; then
-    selected_pid=${pids[$selection-1]}
-    sudo kill "$selected_pid"
-    echo "Executed 'sudo kill' on PID $selected_pid."
-else
-    echo "Invalid selection."
-fi
